### ISSUE TITLE
How do I run the model?

### ISSUE THREAD

**Issue by bio-rat** [zaixizhang/FAIR#1]
Hi first sorry for asking a seemingly dumb question. I am new to the deep learning space from a biochemist background. The provided code only have "train.py" and "test.py" but no easy "inference.py" that specify which type of inputs to feed into the model.

Thank you!

**Comment by GanQiao1990** [comment]
i also seek the information

**Comment by bio-rat** [comment]
If the author doesn't respond soon I will write my own inference.py in a few days!

**Comment by zaixizhang** [comment]
Thanks for your question! In the test.py, the input is the test split of the processed protein and ligand molecule data. We are developing code that can design protein pocket for new protein-ligand data not in the processed dataset.

**Comment by bio-rat** [comment]
Oh thank you for the response. When will the code for that be available? I really appreciate your work on this and it may apply to my current problem so I wish you the best!

**Comment by zaixizhang** [comment]
It may take several weeks. I am working on other projects and thanks for your patience.
