### ISSUE TITLE
Suspectable logic of the codes

### ISSUE THREAD

**Issue by sea2023time** [zaixizhang/FAIR#3]
Hi Zaixi,   

https://github.com/zaixizhang/FAIR/issues/2.  
As mentioned in the above issue, there seems to be a huge discrepancy between the methods and the implementation.  
Your response does not address my concern.   

Let's see the part of the codes for generating the backbone.   
https://github.com/zaixizhang/FAIR/blob/main/models/PD.py#L226-L238  

Let's see the codes step by step.  
In each iteration, the predicted `pred_X` is only used for updating `batch['protein_pos']`.   
However, in https://github.com/zaixizhang/FAIR/blob/main/models/encoders/cftfm.py#L328, the `batch['residue_pos']` is used instead of `batch['protein_pos']` or anything that depends on that.   
Furthermore,  see https://github.com/zaixizhang/FAIR/blob/main/models/protein_features.py#L224-L242, where the ground truth backbone atom positions are used to **construct the knn graph and build the edge features** (which actually contains almost all the geometric information of the backbone). And you further use these features to predict the so-called backbone atom positions. It's unreasonable. **This makes the task nearly sequence design given a fixed backbone.**   
Thus the results of this paper are all suspectable.   

Please give a reasonable explanation.   
Looking forward to your reply.

**Comment by zaixizhang** [comment]
Hi,

Thanks for your response! Could you provide your results and observations? Since we are still working on this project, the GitHub repo contains the preliminary version of our work for reference.

**Comment by zaixizhang** [comment]
Hi,

Thanks for your question. In our paper, we do the full atom protein pocket design instead of only reproducing the backbone atom positions. The method in our paper and implementation are consistent. I am sorry for some confusion brought to you.

**Comment by zaixizhang** [comment]
As one of the first few papers in this area, it is challenging to formulate the problem. We will further polish our method and paper to make it easier to understand. Thanks for your feedback.

**Comment by sea2023time** [comment]
Thanks for your reply.   

But it is nothing about formulation.   
The research problem is clearly formulated and very easy to follow. And the writing of this paper is good.   
It is about structure-sequence co-design for pockets. There are two stages of this method: the first one is for backbone refinement. The unknown 3D structure (specifically, the backbone atom positions) of the pocket is initialized in the way mentioned in the appendix of the paper. And the backbone refinement involves both sequence refinement and structure refinement. The second stage is for full-atom refinement.  Additionally, the baselines are also under this setting according to the paper.  All results are reported under this setting.

**However, the codebase is a totally different setting**. And the logic of the codes is unreasonable. I think it is clear.   
And I do not think it is confusing at all.

**Comment by zaixizhang** [comment]
Thanks for sharing your understanding of our work! FAIR regenerates both the sequence and the full atom coordinates, which is the setting of co-design. In the future version, we will not use the backbone structure for reference for more flexible generation.

**Comment by zaixizhang** [comment]
We will further clarify the use of residue_pos in the camera-ready version of the main paper. Thanks for your feedback!

**Comment by sea2023time** [comment]
> Thanks for sharing your understanding of our work! FAIR regenerates both the sequence and the full atom coordinates, which is the setting of co-design. In the future version, we will not use the backbone structure for reference for more flexible generation.

In your paper, the setting is completely another one.   
It is suspectable that you might have misled the reviewers on purpose and cheated by incorporating ground truth backbone structures.    
The problem definition in your paper is very easy to follow but conflicts with the codebase.   

It is not a qualified paper as a published one on NeurIPS and needs to be re-evaluated by peer reviews.   
It's so frustrating.
